groupName: acme.scaleway.com

certManager:
  namespace: cert-manager
  serviceAccountName: cert-manager

image:
  repository: scaleway/cert-manager-webhook-scaleway
  pullPolicy: IfNotPresent
  imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

pki:
  caDuration: 43800h # 5y
  servingCertificateDuration: 8760h # 1y

secret:
  accessKey: ""
  secretKey: ""
  name: scaleway-webhook-secret

service:
  type: ClusterIP
  port: 443

resources:
  limits:
   cpu: 100m
   memory: 128Mi
  requests:
   cpu: 100m
   memory: 128Mi
