apiVersion: v1
data:
  name: amV0c3RhY2s=
  project: ZGVmYXVsdA==
  type: aGVsbQ==
  url: aHR0cHM6Ly9jaGFydHMuamV0c3RhY2suaW8=
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-4544843245
  namespace: argocd
type: Opaque