apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  sources:
  - repoURL: 'git@github.com:SoulKyu/UJMS.git'
    path: argocd/repository
    targetRevision: main
  - repoURL: 'git@github.com:SoulKyu/UJMS.git'
    path: argocd/applications
    targetRevision: main