apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyseerr
  namespace: argocd
spec:
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: jellyseerr
  sources:
  - repoURL: 'git@github.com:SoulKyu/UJMS.git'
    path: jellyseerr
    targetRevision: main