apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flaresolver
  namespace: argocd
spec:
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: flaresolver
  sources:
  - repoURL: 'git@github.com:SoulKyu/UJMS.git'
    path: flaresolver
    targetRevision: main