apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  sources:
  - repoURL: 'https://charts.jetstack.io'
    chart: cert-manager
    targetRevision: 1.12.1
    helm:
      valueFiles:
      - $values/cert-manager/values.yaml
  - repoURL: 'git@github.com:SoulKyu/UJMS.git'
    targetRevision: main
    ref: values