apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: radarr
  namespace: argocd
spec:
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=trues
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: radarr
  sources:
  - repoURL: 'git@github.com:SoulKyu/UJMS.git'
    path: radarr
    targetRevision: main