apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  sources:
  - repoURL: 'https://kubernetes.github.io/ingress-nginx'
    chart: ingress-nginx
    targetRevision: 4.7.0
    helm:
      valueFiles:
      - $values/ingress-nginx/values.yaml
  - repoURL: 'git@github.com:SoulKyu/UJMS.git'
    targetRevision: main
    ref: values